"""Assemble the generated feed into one runnable Databricks notebook.

Deterministic (Layer 1): the notebook is built from the already-rendered
module sources — no clock, no randomness, fixed cell ids — so emitting twice
is byte-identical. The module files under ``pipeline/`` remain the canonical,
tested source; the notebook is the consolidated deliverable.

Cells keep module source verbatim (banner comments aside). A small bootstrap
cell creates a ``pipeline`` package in ``sys.modules`` and each module cell
ends with a ``_nb_publish(...)`` call that registers the names it defined as
``pipeline.<module>``, so the modules' own ``from pipeline import ...`` lines
work unmodified when the notebook runs top to bottom.

That single-namespace execution is only sound if no two modules bind the same
top-level name to different things. ``_check_namespace`` proves it from the
AST at build time and raises :class:`TemplateGapError` otherwise — the gate
FAILs instead of emitting a notebook that silently shadows names.
"""

from __future__ import annotations

import ast
import json
from typing import Any

from codegen.emit.context import TemplateGapError

_BANNER_PREFIX = "# GENERATED by"
_COMMAND_MARKER = "# COMMAND ----------"
_DATABRICKS_HEADER = "# Databricks notebook source"

# Names the bootstrap and DDL cells own; no module may bind them.
_RESERVED_NAMES = {
    "_nb_sys",
    "_nb_types",
    "_nb_pipeline",
    "_nb_publish",
    "_nb_ddl_statements",
    "_nb_ddl_statement",
}


class _Bindings:
    """Top-level names one module binds: definitions and import aliases."""

    def __init__(self, defs: list[str], aliases: dict[str, str]) -> None:
        self.defs = defs
        self.aliases = aliases


def _top_level_bindings(module_label: str, source: str) -> _Bindings:
    defs: list[str] = []
    aliases: dict[str, str] = {}

    def add_def(name: str) -> None:
        if name not in defs:
            defs.append(name)

    tree = ast.parse(source, filename=module_label)
    for node in tree.body:
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
            add_def(node.name)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                for name_node in ast.walk(target):
                    if isinstance(name_node, ast.Name):
                        add_def(name_node.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            add_def(node.target.id)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                bound = alias.asname if alias.asname else alias.name.partition(".")[0]
                aliases[bound] = alias.name if alias.asname else bound
        elif isinstance(node, ast.ImportFrom):
            module = node.module if node.module else ""
            for alias in node.names:
                bound = alias.asname if alias.asname else alias.name
                aliases[bound] = f"{module}.{alias.name}"
    return _Bindings(defs, aliases)


def _check_namespace(bindings_by_label: dict[str, _Bindings]) -> None:
    """Prove the shared notebook namespace is collision-free."""
    def_owner: dict[str, str] = {}
    alias_target: dict[str, tuple[str, str]] = {}
    for label, bindings in bindings_by_label.items():
        for name in [*bindings.defs, *bindings.aliases]:
            if name in _RESERVED_NAMES:
                raise TemplateGapError(
                    f"{label} binds {name!r}, reserved by the notebook bootstrap"
                )
        for name in bindings.defs:
            if name in def_owner:
                raise TemplateGapError(
                    f"notebook namespace collision: {label} and {def_owner[name]} "
                    f"both define {name!r}"
                )
            def_owner[name] = label
        for name, target in bindings.aliases.items():
            seen = alias_target.get(name)
            if seen is not None and seen[1] != target:
                raise TemplateGapError(
                    f"notebook namespace collision: {label} imports {name!r} as "
                    f"{target!r} but {seen[0]} imports it as {seen[1]!r}"
                )
            alias_target[name] = (label, target)
    for name, (label, _target) in alias_target.items():
        if name in def_owner and def_owner[name] != label:
            raise TemplateGapError(
                f"notebook namespace collision: {def_owner[name]} defines {name!r} "
                f"but {label} imports it"
            )


def _check_import_order(
    ordered_modules: list[str], bindings_by_label: dict[str, _Bindings]
) -> None:
    """Cells run top to bottom — every pipeline import must already be published."""
    seen: set[str] = set()
    published = dict.fromkeys(ordered_modules)
    for label, bindings in bindings_by_label.items():
        module_name = label.removeprefix("pipeline/").removesuffix(".py")
        for target in bindings.aliases.values():
            if not target.startswith("pipeline."):
                continue
            imported = target.removeprefix("pipeline.")
            if imported in published and imported not in seen:
                raise TemplateGapError(
                    f"{label} imports pipeline.{imported} before its cell runs; "
                    f"notebook cell order cannot satisfy it"
                )
        if module_name in published:
            seen.add(module_name)


def _strip_banner(source: str) -> str:
    lines = source.splitlines()
    start = next((i for i, line in enumerate(lines) if line.startswith(_BANNER_PREFIX)), None)
    if start is None:
        return source
    end = start
    while end < len(lines) and lines[end].startswith("#"):
        end += 1
    return "\n".join([*lines[:start], *lines[end:]]) + ("\n" if source.endswith("\n") else "")


def _source_lines(text: str) -> list[str]:
    return text.splitlines(keepends=True)


def _md_cell(cell_id: str, text: str) -> dict[str, Any]:
    return {
        "cell_type": "markdown",
        "id": cell_id,
        "metadata": {},
        "source": _source_lines(text),
    }


def _code_cell(cell_id: str, text: str) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "id": cell_id,
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": _source_lines(text),
    }


def _intro_cell(context: dict[str, Any]) -> dict[str, Any]:
    feed = context["feed"]
    provenance = context["provenance"]
    lines = [
        f"# `{feed['slug']}` — ingestion pipeline notebook",
        "",
        "> GENERATED by codegen-data-engineer-agent — DO NOT EDIT BY HAND.",
        "> Assembled from the generated `pipeline/` modules; those files remain the",
        "> canonical, tested source. Regenerate from the contracts instead.",
        "",
        f"**Feed:** {feed['id']} ({feed['name']}) — {feed['source_system']}",
        "",
        f"**FRD contract:** {provenance['frd_name']} — sha256 `{provenance['frd_sha'][:16]}`",
        "",
        f"**STTM contract:** sha256 `{provenance['sttm_sha'][:16]}`",
    ]
    if provenance["synthetic"]:
        lines += [
            "",
            "**WARNING:** the STTM contract is SYNTHETIC — regenerate when the real",
            "mapping workbook extract lands.",
        ]
    inputs = provenance["inputs"]
    if inputs["dataset_source"] or inputs["dataset_target"]:
        dataset_line = (
            f"source={inputs['dataset_source'] or '?'} target={inputs['dataset_target'] or '?'}"
        )
    else:
        dataset_line = "not yet integrated (planned)"
    lines += [
        "",
        "**Inputs (three-input model):**",
        "",
        f"- STTM contract: sha256 `{provenance['sttm_sha'][:16]}`",
        f"- Engineering standards: {inputs['standards_status']}",
        f"- Load-pattern FAQ: {inputs['answered']} answered "
        f"({inputs['from_contract']} from contract), {inputs['unknown']} unknown",
        f"- Collibra dataset IDs: {dataset_line}",
        "",
        f"**Declared load mode:** {inputs['load_mode']} (source: {inputs['load_mode_source']})",
        "",
        f"**Write behavior in this version:** {inputs['writer_behavior']} "
        "(load-mode branching: v2)",
    ]
    lines += [
        "",
        "Run top to bottom on Databricks. Each module cell registers itself as",
        "`pipeline.<module>`, so the code runs unmodified; the final cells are the",
        "job entrypoint (widgets → orchestrator).",
    ]
    return _md_cell("intro", "\n".join(lines) + "\n")


def _bootstrap_cell(context: dict[str, Any]) -> dict[str, Any]:
    slug = context["feed"]["slug"]
    text = (
        "import sys as _nb_sys\n"
        "import types as _nb_types\n"
        "\n"
        '_nb_pipeline = _nb_types.ModuleType("pipeline")\n'
        "_nb_pipeline.__path__ = []\n"
        f'_nb_pipeline.__doc__ = "Generated ingestion pipeline for {slug} (notebook-assembled)."\n'
        '_nb_sys.modules["pipeline"] = _nb_pipeline\n'
        "\n"
        "\n"
        "def _nb_publish(module_name, names):\n"
        '    """Register the names the preceding cell defined as pipeline.<module_name>."""\n'
        '    module = _nb_types.ModuleType(f"pipeline.{module_name}")\n'
        "    for name in names:\n"
        "        setattr(module, name, globals()[name])\n"
        '    _nb_sys.modules[f"pipeline.{module_name}"] = module\n'
        "    setattr(_nb_pipeline, module_name, module)\n"
    )
    return _code_cell("bootstrap", text)


def _strip_sql_banner(sql: str) -> str:
    """Drop the leading provenance comments (GENERATED / Feed / sha256 lines);
    semantic ``--`` notes that follow them stay."""
    lines = sql.splitlines()
    if not lines or not lines[0].startswith("-- GENERATED by"):
        return sql
    end = 0
    while end < len(lines) and lines[end].startswith("--"):
        is_sha_line = "sha256" in lines[end]
        end += 1
        if is_sha_line:
            break
    return "\n".join(lines[end:])


def _ddl_cells(ddl_sources: list[tuple[str, str]]) -> list[dict[str, Any]]:
    if not ddl_sources:
        return []
    md = _md_cell(
        "ddl-md",
        "## DDL — target tables\n\nRun once per target environment; every statement is"
        " `CREATE TABLE IF NOT EXISTS`, so re-running is safe.\n",
    )
    parts = ["_nb_ddl_statements = ["]
    for name, sql in ddl_sources:
        if '"""' in sql:
            raise TemplateGapError(f"DDL {name} contains a triple quote; cannot embed in notebook")
        parts.append(f"    # {name}")
        parts.append(f'    """{_strip_sql_banner(sql).strip()}""",')
    parts.append("]")
    parts.append("")
    parts.append("for _nb_ddl_statement in _nb_ddl_statements:")
    parts.append("    spark.sql(_nb_ddl_statement)  # noqa: F821 - spark exists on Databricks")
    return [md, _code_cell("ddl", "\n".join(parts) + "\n")]


def _prerequisite_cell(context: dict[str, Any]) -> dict[str, Any]:
    """Under create_tables=false the notebook creates nothing — it lists the
    tables the target environment must already have (MVP prerequisite)."""
    prefix = f"{context['default_catalog']}." if context["default_catalog"] else ""
    schema = context["stage_schema"]
    tables = [f"{prefix}{schema}.{seg['stage_table']}" for seg in context["segments"]]
    tables.append(f"{prefix}{schema}.{context['errors_table']}")
    tables.append(f"{prefix}{schema}.{context['processed_files_table']}")
    if context["recycle"]:
        tables.append(f"{prefix}{schema}.{context['recycle']['table']}")
    if context["standard"]:
        std = context["standard"]
        std_prefix = f"{std['catalog']}." if std["catalog"] else ""
        tables.append(f"{std_prefix}{std['schema']}.{std['table']}")
    text = (
        "## Prerequisite tables (create_tables=false)\n"
        "\n"
        "MVP prerequisite: these tables must already exist in the target\n"
        "environment. The `ddl/` files are emitted for REFERENCE only and are\n"
        "not executed by this notebook.\n"
        "\n" + "\n".join(f"- `{table}`" for table in tables) + "\n"
    )
    return _md_cell("prerequisites", text)


def _module_cells(name: str, source: str, bindings: _Bindings) -> list[dict[str, Any]]:
    docstring = ast.get_docstring(ast.parse(source))
    summary = docstring.strip().splitlines()[0] if docstring else ""
    md_text = f"## `pipeline/{name}.py`"
    if summary:
        md_text += f"\n\n{summary}"
    body = _strip_banner(source).rstrip("\n")
    publish = [f'_nb_publish("{name}", [']
    publish += [f'    "{def_name}",' for def_name in bindings.defs]
    publish.append("])")
    code = body + "\n\n\n" + "\n".join(publish) + "\n"
    return [_md_cell(f"{name}-md", md_text + "\n"), _code_cell(name, code)]


def _entrypoint_cells(entrypoint_source: str) -> list[dict[str, Any]]:
    text = _strip_banner(entrypoint_source)
    lines = [line for line in text.splitlines() if line.strip() != _DATABRICKS_HEADER]
    chunks: list[list[str]] = [[]]
    for line in lines:
        if line.strip() == _COMMAND_MARKER:
            chunks.append([])
        else:
            chunks[-1].append(line)
    cells = [
        _md_cell(
            "entrypoint-md",
            "## Job entrypoint\n\nWidgets → orchestrator; identical to"
            " `job/notebook_entrypoint.py`.\n",
        )
    ]
    index = 0
    for chunk in chunks:
        cell_text = "\n".join(chunk).strip("\n")
        if not cell_text:
            continue
        cells.append(_code_cell(f"entrypoint-{index}", cell_text + "\n"))
        index += 1
    return cells


def build_notebook(
    context: dict[str, Any],
    module_sources: list[tuple[str, str]],
    ddl_sources: list[tuple[str, str]],
    entrypoint_source: str,
) -> str:
    """Return the notebook as JSON text; raises TemplateGapError on unsound input."""
    bindings_by_label = {
        f"pipeline/{name}.py": _top_level_bindings(f"pipeline/{name}.py", source)
        for name, source in module_sources
    }
    bindings_by_label["job/notebook_entrypoint.py"] = _top_level_bindings(
        "job/notebook_entrypoint.py", entrypoint_source
    )
    _check_namespace(bindings_by_label)
    _check_import_order([name for name, _ in module_sources], bindings_by_label)

    cells = [_intro_cell(context), _bootstrap_cell(context)]
    if context["standards"]["create_tables"]:
        cells += _ddl_cells(ddl_sources)
    else:
        cells.append(_prerequisite_cell(context))
    for name, source in module_sources:
        cells += _module_cells(name, source, bindings_by_label[f"pipeline/{name}.py"])
    cells += _entrypoint_cells(entrypoint_source)

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, ensure_ascii=False, indent=1) + "\n"
