"""`rfc` output mode (M5): assemble one RFC deployment package per feed.

``RFC<number>_<Feed>/`` — the INGESTION-family folder tree documented in
docs/acfc/rfc_capture/.../RFC_PACKAGE_SHAPES.md §1:

* the deployment DDL exactly as the active conventions profile emitted it
  (two files under ``edo_sfmc``, one combined file under ``acfc_prx``),
  renamed to the package's feed token;
* ``<Feed>_IIG.xlsx`` — the active IIG template's sheets (the framework
  workbook minus its ``_provenance`` / ``_inputs`` sheets, which stay in
  ``framework/config_rows.xlsx``, the approval artefact);
* ``RFC<number>_<Feed>_Deployment_Playbook.xlsx`` from the active playbook
  template: task rows from the config list (per conventions profile), the
  RFC# column from the run input, every date / time / owner / team /
  status / contact cell blank AND flagged;
* ``FILE_LOG_INFORMATION.txt`` (T-SQL, documented shape) when
  ``rfc.file_log_information`` is on;
* ``MANIFEST.md`` — every file written, its source artefact, the flags that
  apply to it, and the out-of-scope lines for the Runbook and TDD.

Nothing here reads a document or a model: it re-arranges artefacts the
framework emit produced and fills templates from config + FAQ answers.
The RFC number and the feed token come from the load-pattern FAQ
(``rfc_number`` / ``feed_abbreviation``); unanswered → documented
placeholder + flag, never invented.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path

from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font

from codegen.config import Config, PlaybookTasksConfig, PlaybookTemplateConfig
from codegen.contracts.resolved import ResolvedFeedSpec
from codegen.emit.framework import FrameworkArtefacts, _sanitize_abbrev
from codegen.faq import LoadPatternFaq
from codegen.metadata_sheet import _pin_workbook_properties, stable_workbook_bytes

# Task-row columns the config / run input fill; every other header on a task
# sheet is blank-and-flag.
_FILLED_HEADERS = {"#", "Task #", "Task", "Task Detail", "Detail", "RFC#s"}
_MANIFEST_TEMPLATE = """\
# RFC package — {package_dir}

Assembled by the `rfc` output mode from the framework artefacts of feed
`{slug}` (conventions profile `{profile}`, IIG template `{iig_template}`,
playbook template `{playbook_template}`). Every value is transcribed from a
run input or a config/FAQ entry; blanks are flagged, never filled.

- RFC number: {rfc_display}
- Feed token: {feed_display}

| File | Source artefact | Flags that apply |
| --- | --- | --- |
{rows}

Out of scope (not generated by the agent):

- `Operational_RunBook_<Feed>.docx` — operational runbook; authored by the operations team.
- `TDD_<description>.docx` — technical design document; authored by the design owner.
"""


@dataclass(frozen=True)
class RfcArtefacts:
    package_dir: Path
    files: list[Path]
    flags: list[str]
    # file name -> flags that apply (what MANIFEST.md lists)
    applies: dict[str, list[str]] = field(default_factory=dict)


class _Tokens(dict):
    """format_map helper: unknown placeholders render literally."""

    def __missing__(self, key: str) -> str:  # pragma: no cover - trivial
        return "{" + key + "}"


def _answer(faq: LoadPatternFaq, name: str) -> str | None:
    answer = getattr(faq, name, None)
    if answer is None or answer.source == "unknown":
        return None
    value = str(answer.value).strip()
    return value or None


def _rfc_flags_for(name: str, flags: list[str], prefixes: tuple[str, ...]) -> list[str]:
    return [f for f in flags if f.split(":", 1)[0] in prefixes or any(
        f.startswith(p) for p in prefixes)]


# -- playbooks ----------------------------------------------------------------- #


def _task_rows(tasks: PlaybookTasksConfig, section: str, tokens: dict) -> list[tuple[str, str]]:
    return [(t.task.format_map(_Tokens(tokens)), t.detail.format_map(_Tokens(tokens)))
            for t in getattr(tasks, section)]


def _blank_flags(sheet_title: str, headers: list[str], any_rows: bool) -> list[str]:
    if not any_rows:
        return []
    return [f"playbook_blank:{sheet_title}.{_clean(h)}"
            for h in headers if h and _clean(h) not in _FILLED_HEADERS]


def _clean(header) -> str:
    return re.sub(r"\s+", " ", str(header or "")).strip()


def _write_task_rows(ws, header_row: int, headers: list[str], sections: list[tuple[str, list]],
                     rfc_token: str, number_from: int = 1) -> int:
    """Write section band rows + numbered task rows under the header row;
    returns the number of task rows written."""
    col_of = {_clean(h): i + 1 for i, h in enumerate(headers) if h}
    row = header_row + 1
    written = 0
    for label, rows in sections:
        if label:
            ws.cell(row=row, column=1, value=label).font = Font(bold=True)
            row += 1
        for index, (task, detail) in enumerate(rows, start=number_from):
            ws.cell(row=row, column=col_of.get("#", col_of.get("Task #", 1)), value=index)
            ws.cell(row=row, column=col_of["Task"], value=task)
            detail_col = col_of.get("Task Detail", col_of.get("Detail"))
            if detail_col is not None:
                ws.cell(row=row, column=detail_col, value=detail)
            if "RFC#s" in col_of:
                ws.cell(row=row, column=col_of["RFC#s"], value=rfc_token)
            row += 1
            written += 1
        if label:
            row += 1  # blank spacer after a section, as the reference lays it out
    return written


def _clear_below(ws, header_row: int) -> None:
    """Drop every row under the header (task rows, band rows, stray cells),
    un-merging anything that spans them first."""
    for merged in list(ws.merged_cells.ranges):
        if merged.max_row > header_row:
            ws.unmerge_cells(str(merged))
    if ws.max_row > header_row:
        ws.delete_rows(header_row + 1, ws.max_row - header_row)


def _headers(ws, header_row: int) -> list[str]:
    return [("" if c.value is None else str(c.value)) for c in ws[header_row]]


def _build_sfmc_7sheet(tpl: PlaybookTemplateConfig, tasks: PlaybookTasksConfig,
                       tokens: dict, rfc_token: str, base_dir: Path) -> tuple[bytes, list[str]]:
    source = Path(tpl.source or "")
    if not source.is_absolute():
        source = base_dir / source
    if not source.is_file():
        raise FileNotFoundError(
            f"playbook template source not found: {source} (playbook.templates.*.source)")
    wb = load_workbook(source)
    flags: list[str] = []

    # Overview: a day/time schedule grid of the reference deployment — every
    # cell is a date, a time or a person; nothing here states them.
    if tpl.overview_sheet and tpl.overview_sheet in wb.sheetnames:
        ws = wb[tpl.overview_sheet]
        for merged in list(ws.merged_cells.ranges):
            ws.unmerge_cells(str(merged))
        for row in ws.iter_rows():
            for cell in row:
                cell.value = None
        flags.append(f"playbook_blank:{tpl.overview_sheet}.schedule grid")

    # Cover page: keep the template's labels, blank the reference's values.
    if tpl.cover_sheet and tpl.cover_sheet in wb.sheetnames:
        ws = wb[tpl.cover_sheet]
        for coordinate, label in tpl.cover_value_cells.items():
            ws[coordinate].value = None
            flags.append(f"playbook_blank:{tpl.cover_sheet}.{label}")
        for coordinate, label in tpl.cover_label_cells.items():
            ws[coordinate].value = label

    # Task sheets: header rows stay verbatim; task rows come from config.
    task_sections = [
        (tpl.section_labels.get("pre_production", "PRE-PRODUCTION"),
         _task_rows(tasks, "pre_production", tokens)),
        (tpl.section_labels.get("production", "PRODUCTION"),
         _task_rows(tasks, "production", tokens)),
        (tpl.section_labels.get("post_production", "POST PRODUCTION"),
         _task_rows(tasks, "post_production", tokens)),
    ]
    for sheet_name, sections in (
            (tpl.task_sheet, task_sections),
            (tpl.rollback_execution_sheet,
             [(tpl.section_labels.get("rollback_execution", "BACKOUT/ROLLBACK EXECUTION"),
               _task_rows(tasks, "rollback_execution", tokens))]),
            (tpl.rollback_validation_sheet,
             [(tpl.section_labels.get("rollback_validation", "BACKOUT/ROLLBACK VALIDATION"),
               _task_rows(tasks, "rollback_validation", tokens))]),
    ):
        if not sheet_name or sheet_name not in wb.sheetnames:
            continue
        ws = wb[sheet_name]
        headers = _headers(ws, tpl.header_row)
        _clear_below(ws, tpl.header_row)
        written = _write_task_rows(ws, tpl.header_row, headers, sections, rfc_token)
        flags += _blank_flags(sheet_name, headers, written > 0)

    # Contact list: header only — names, phones and escalation points are
    # people; the agent never fills them.
    if tpl.contact_sheet and tpl.contact_sheet in wb.sheetnames:
        ws = wb[tpl.contact_sheet]
        headers = _headers(ws, 1)
        _clear_below(ws, 1)
        flags += [f"playbook_blank:{tpl.contact_sheet}.{_clean(h)}" for h in headers if h]

    _pin_workbook_properties(wb)
    return stable_workbook_bytes(wb), flags


def _build_main_single(tpl: PlaybookTemplateConfig, tasks: PlaybookTasksConfig,
                       tokens: dict, rfc_token: str) -> tuple[bytes, list[str]]:
    wb = Workbook()
    _pin_workbook_properties(wb)
    ws = wb.active
    ws.title = tpl.sheet
    headers = list(tpl.headers)
    for index, header in enumerate(headers, start=1):
        if header:
            ws.cell(row=1, column=index, value=header).font = Font(bold=True)
    rows = []
    for section in ("pre_production", "production", "post_production",
                    "rollback_execution", "rollback_validation"):
        rows += _task_rows(tasks, section, tokens)
    written = _write_task_rows(ws, 1, headers, [("", rows)], rfc_token)
    flags = _blank_flags(tpl.sheet, headers, written > 0)
    return stable_workbook_bytes(wb), flags


# -- FILE_LOG_INFORMATION ------------------------------------------------------ #


def _file_log_text(config: Config) -> tuple[str, list[str]]:
    rfc = config.rfc
    lines = [rfc.file_log_header_line]
    lines += [f"  {column}{',' if i < len(rfc.file_log_columns) else ''}"
              for i, column in enumerate(rfc.file_log_columns, start=1)]
    lines.append(")")
    flags = []
    if any("<" in column for column in rfc.file_log_columns):
        flags.append("file_log_placeholder_unstated: the documented FILE_LOG_INFORMATION "
                     "shape masks a value (e.g. the varchar length as <length>); transcribed "
                     "as documented, the deployment team supplies it")
    return "\n".join(lines) + "\n", flags


# -- package ------------------------------------------------------------------- #


def emit_rfc_package(
    spec: ResolvedFeedSpec,
    faq: LoadPatternFaq,
    config: Config,
    out_root: Path,
    framework: FrameworkArtefacts,
    *,
    flags_so_far: list[str],
    conventions_profile: str | None = None,
    iig_template: str | None = None,
    playbook_template: str | None = None,
    base_dir: Path | None = None,
) -> RfcArtefacts:
    rfc = config.rfc
    base = base_dir if base_dir is not None else Path(".")
    profile_name = conventions_profile or config.conventions.profile
    iig_name = iig_template or config.metadata.template
    playbook_name, playbook_tpl = config.playbook.resolve(playbook_template)
    tasks = config.playbook.tasks_for(profile_name)
    flags: list[str] = []

    rfc_number = _answer(faq, "rfc_number")
    if rfc_number is None:
        rfc_number = rfc.number_placeholder
        flags.append(f"rfc_number_unanswered: no rfc_number in the load-pattern FAQ; the "
                     f"package uses the documented placeholder {rfc.number_placeholder!r}")
    feed = _answer(faq, "feed_abbreviation")
    if feed is None:
        feed = _sanitize_abbrev(spec.feed_slug)
        flags.append(f"rfc_feed_name_from_slug: no feed_abbreviation in the load-pattern FAQ; "
                     f"package names use {feed!r} from the feed slug")
    tokens = {"rfc_number": rfc_number, "feed_slug": feed, "feed": feed,
              "rfc": f"RFC{rfc_number}"}
    package_dir = out_root / spec.feed_slug / rfc.dir_pattern.format_map(_Tokens(tokens))
    if package_dir.exists():
        shutil.rmtree(package_dir)
    package_dir.mkdir(parents=True)

    files: list[Path] = []
    applies: dict[str, list[str]] = {}
    sources: dict[str, str] = {}

    # 1. DDL exactly as the profile emitted it, under the package feed token.
    ddl_names: list[str] = []
    for path in framework.files:
        if not path.name.endswith(".txt") or not path.is_file():
            continue
        name = path.name
        if name.startswith(f"{spec.feed_slug}_") and name.endswith("_table_creation.txt"):
            name = f"{feed}_{name[len(spec.feed_slug) + 1:]}"
        target = package_dir / name
        shutil.copyfile(path, target)
        files.append(target)
        ddl_names.append(name)
        sources[name] = f"framework/{path.name}"
        applies[name] = _rfc_flags_for(name, [*flags_so_far, *flags], (
            "drag_fill_suspect", "segments_from_sttm", "file_pattern_from_sttm",
            "ddl_file_name_from_slug", "rfc_feed_name_from_slug"))
    tokens["ddl_files"] = ", ".join(ddl_names)

    # 2. IIG: the template sheets only (provenance stays in config_rows.xlsx).
    rows_path = next((p for p in framework.files if p.name == "config_rows.xlsx"), None)
    if rows_path is not None:
        iig_name_out = rfc.iig_file_name.format_map(_Tokens(tokens))
        wb = load_workbook(rows_path)
        for sheet_name in list(wb.sheetnames):
            if sheet_name.startswith("_"):
                del wb[sheet_name]
        _pin_workbook_properties(wb)
        target = package_dir / iig_name_out
        target.write_bytes(stable_workbook_bytes(wb))
        files.append(target)
        sources[iig_name_out] = "framework/config_rows.xlsx (minus _provenance / _inputs)"
        applies[iig_name_out] = _rfc_flags_for(
            iig_name_out, [*flags_so_far, *flags], ("iig_blank", "rfc_feed_name_from_slug"))
        tokens["iig_file"] = iig_name_out

    # 3. Playbook.
    playbook_file = rfc.playbook_file_name.format_map(_Tokens(tokens))
    if playbook_tpl.kind == "sfmc_7sheet":
        data, playbook_flags = _build_sfmc_7sheet(playbook_tpl, tasks, tokens,
                                                  f"RFC{rfc_number}", base)
        source = f"playbook template {playbook_name} ({playbook_tpl.source}) + config tasks"
    else:
        data, playbook_flags = _build_main_single(playbook_tpl, tasks, tokens,
                                                  f"RFC{rfc_number}")
        source = (f"playbook template {playbook_name} (single sheet {playbook_tpl.sheet!r}) "
                  "+ config tasks")
    flags += playbook_flags
    target = package_dir / playbook_file
    target.write_bytes(data)
    files.append(target)
    sources[playbook_file] = source
    applies[playbook_file] = [f for f in flags
                              if f.startswith("playbook_blank:") or f.startswith("rfc_")]

    # 4. FILE_LOG_INFORMATION.txt (documented T-SQL shape) when enabled.
    if rfc.file_log_information:
        text, log_flags = _file_log_text(config)
        flags += log_flags
        target = package_dir / rfc.file_log_file_name
        target.write_text(text, encoding="utf-8", newline="\n")
        files.append(target)
        sources[rfc.file_log_file_name] = "config rfc.file_log_columns (RFC_PACKAGE_SHAPES §1)"
        applies[rfc.file_log_file_name] = log_flags

    # 5. MANIFEST.md.
    manifest_rows = []
    for path in files:
        applying = applies.get(path.name, [])
        counts: dict[str, int] = {}
        for flag in applying:
            key = flag.split(":", 1)[0]
            counts[key] = counts.get(key, 0) + 1
        flag_cell = "; ".join(f"`{k}`" + (f" ×{n}" if n > 1 else "")
                              for k, n in counts.items()) or "none"
        manifest_rows.append(f"| `{path.name}` | {sources.get(path.name, '')} | {flag_cell} |")
    manifest = package_dir / rfc.manifest_file_name
    manifest.write_text(_MANIFEST_TEMPLATE.format(
        package_dir=package_dir.name, slug=spec.feed_slug, profile=profile_name,
        iig_template=iig_name, playbook_template=playbook_name,
        rfc_display=(f"RFC{rfc_number}" if "rfc_number_unanswered" not in
                     " ".join(flags) else f"RFC{rfc_number} (placeholder — unanswered)"),
        feed_display=(feed if "rfc_feed_name_from_slug" not in " ".join(flags)
                      else f"{feed} (from the feed slug — no feed_abbreviation)"),
        rows="\n".join(manifest_rows)), encoding="utf-8", newline="\n")
    files.append(manifest)
    return RfcArtefacts(package_dir=package_dir, files=files, flags=flags, applies=applies)


def report_section(artefacts: RfcArtefacts) -> str:
    lines = [
        "",
        f"## RFC package (`{artefacts.package_dir.name}/`)",
        "",
        "| File | Flags that apply |",
        "| --- | --- |",
    ]
    for path in artefacts.files:
        applying = artefacts.applies.get(path.name, [])
        lines.append(f"| `{path.name}` | {len(applying)} |")
    return "\n".join(lines) + "\n"


__all__ = ["RfcArtefacts", "emit_rfc_package", "report_section"]
