"""Notebook assembly: structure, verbatim-source guarantees, namespace guards."""

from __future__ import annotations

import json

import pytest

from codegen.emit.context import TemplateGapError, build_context
from codegen.emit.emitter import emit_feed
from codegen.emit.notebook import build_notebook


def _context(spec, config):
    return build_context(
        spec,
        config,
        allow_duplicate_file_name=True,
        duplicate_rule_text=None,
        notification_rule_texts=[],
    )


@pytest.fixture(scope="module")
def caqh_notebook(specs_by_id, config, tmp_path_factory):
    spec = specs_by_id["caqh_tpl_inbound_files"]
    out_root = tmp_path_factory.mktemp("nb")
    written = emit_feed(_context(spec, config), out_root)
    path = out_root / spec.feed_slug / f"{spec.feed_slug}.ipynb"
    assert path in written
    return json.loads(path.read_text(encoding="utf-8"))


def test_notebook_is_valid_nbformat(caqh_notebook):
    assert caqh_notebook["nbformat"] == 4
    for cell in caqh_notebook["cells"]:
        assert cell["cell_type"] in {"markdown", "code"}
        assert isinstance(cell["source"], list)
    ids = [cell["id"] for cell in caqh_notebook["cells"]]
    assert len(ids) == len(set(ids)), "cell ids must be unique"


def test_notebook_covers_every_pipeline_module(caqh_notebook):
    text_by_id = {c["id"]: "".join(c["source"]) for c in caqh_notebook["cells"]}
    for module in ["feed_spec", "segments", "reader", "recycle", "orchestrator"]:
        assert module in text_by_id
        assert f'_nb_publish("{module}", [' in text_by_id[module]
    # Module source stays verbatim: the intra-package imports survive.
    assert "from pipeline import feed_spec, reference" in text_by_id["recycle"]


def test_notebook_banner_only_in_intro(caqh_notebook):
    hits = [
        cell["id"]
        for cell in caqh_notebook["cells"]
        if "GENERATED by codegen-data-engineer-agent" in "".join(cell["source"])
    ]
    assert hits == ["intro"], "provenance banner belongs to the intro cell only"


def test_notebook_ddl_and_entrypoint_cells(caqh_notebook):
    text_by_id = {c["id"]: "".join(c["source"]) for c in caqh_notebook["cells"]}
    assert "CREATE TABLE IF NOT EXISTS" in text_by_id["ddl"]
    assert "spark.sql(_nb_ddl_statement)" in text_by_id["ddl"]
    entry_cells = [i for i in text_by_id if i.startswith("entrypoint-")]
    assert entry_cells, "entrypoint cells missing"
    assert any("dbutils.widgets" in text_by_id[i] for i in entry_cells)
    assert not any("# COMMAND ----------" in text_by_id[i] for i in entry_cells)


def _minimal_notebook(context, modules):
    return build_notebook(
        context,
        module_sources=modules,
        ddl_sources=[],
        entrypoint_source="from pipeline import orchestrator\n",
    )


def test_defining_same_name_twice_is_a_gap(specs_by_id, config):
    context = _context(specs_by_id["sd_community_risk"], config)
    modules = [("a", "X = 1\n"), ("b", "X = 2\n"), ("orchestrator", "Y = 1\n")]
    with pytest.raises(TemplateGapError, match="both define 'X'"):
        _minimal_notebook(context, modules)


def test_conflicting_import_alias_is_a_gap(specs_by_id, config):
    context = _context(specs_by_id["sd_community_risk"], config)
    modules = [
        ("a", "from datetime import datetime\n"),
        ("b", "import datetime\n"),
        ("orchestrator", "Y = 1\n"),
    ]
    with pytest.raises(TemplateGapError, match="imports 'datetime'"):
        _minimal_notebook(context, modules)


def test_forward_pipeline_import_is_a_gap(specs_by_id, config):
    context = _context(specs_by_id["sd_community_risk"], config)
    modules = [
        ("a", "from pipeline import late\nX = 1\n"),
        ("late", "Y = 1\n"),
        ("orchestrator", "Z = 1\n"),
    ]
    with pytest.raises(TemplateGapError, match="before its cell runs"):
        _minimal_notebook(context, modules)


def test_reserved_bootstrap_name_is_a_gap(specs_by_id, config):
    context = _context(specs_by_id["sd_community_risk"], config)
    modules = [("a", "_nb_publish = 1\n"), ("orchestrator", "Y = 1\n")]
    with pytest.raises(TemplateGapError, match="reserved"):
        _minimal_notebook(context, modules)
