# ruff: noqa: E501  -- fixture data tables: documented header/label texts kept on one line
"""ACFC-shape fixture universe (fixtures/acfc_shapes/) — builders + registry.

Every tracked fixture under ``fixtures/acfc_shapes/`` is generated by one
builder here (byte-stable), so a test can rebuild and compare byte for byte
and the fixture set can never silently drift from its builders. Materialize
with ``python scripts/build_acfc_shapes.py``.
"""

from __future__ import annotations

from pathlib import Path

from . import frd, pair1, sttm, vdd
from .common import xlsx_bytes

REPO = Path(__file__).resolve().parents[2]
FIXTURE_ROOT = REPO / "fixtures" / "acfc_shapes"
GOLDEN_SOURCE = REPO / "docs" / "acfc" / "rfc_capture" / "rfc_capture" / "goldens" / "pair_1"

# fixture path (relative to FIXTURE_ROOT) -> family/pattern -> source pair(s)
FAMILY: dict[str, tuple[str, str]] = {
    "sttm/pair_1_family_a.xlsx": ("STTM family A — inline meta + banded mapping", "pair 1"),
    "sttm/pair_8_family_a.xlsx": ("STTM family A — inline meta + banded mapping", "pair 8"),
    "sttm/pair_2_family_b.xlsx": ("STTM family B — FILE_DETAILS + MAPPING- sheets", "pair 2"),
    "sttm/pair_11_family_b.xlsx": ("STTM family B — FILE_DETAILS + MAPPING- sheets (one-block / many-files FRD)", "pair 11"),
    "sttm/pair_3_family_c.xlsx": ("STTM family C — Layout + STTM dual sheets", "pair 3"),
    "sttm/pair_4_family_d.xlsx": ("STTM family D — single mapping sheet", "pair 4"),
    "sttm/pair_6_family_d.xlsx": ("STTM family D — single mapping sheet", "pair 6"),
    "sttm/pair_5_family_e.xlsx": ("STTM family E — multi-domain / multi-sheet", "pair 5"),
    "sttm/pair_7_family_e.xlsx": ("STTM family E — multi-domain / multi-sheet", "pair 7"),
    "sttm/pair_9_family_e.xlsx": ("STTM family E — multi-domain / multi-sheet", "pair 9"),
    "sttm/pair_10_family_e.xlsx": ("STTM family E — multi-domain / multi-sheet", "pair 10"),
    "frd/f1_pair_1.docx": ("FRD family F1 — six metadata sections (pair-1 label variants)", "pair 1"),
    "frd/f1_pair_2_variant.docx": ("FRD family F1 — six metadata sections (pair-2 label variants)", "pair 2"),
    "frd/f2_pair_8.docx": ("FRD family F2 — Solution Requirement tables", "pairs 8, 9, 10"),
    "frd/f1_pair_11_multi_file.docx": ("FRD family F1 — one metadata block for several files (nested tables, per-file blocks, pointer text; no catalog)", "pair 11"),
    "frd/f1_pair_11_multi_file_catalog.docx": ("FRD family F1 — one metadata block for several files (catalog stated)", "pair 11"),
    "vdd/pair_1_v1_segments.xlsx": ("VDD pattern V1 — full position, Segment column", "pair 1"),
    "vdd/pair_2_v2_per_file.xlsx": ("VDD pattern V2 — length only, one sheet per file", "pair 2"),
    "vdd/pair_9_v3_per_table.xlsx": ("VDD pattern V3 — DB table, one sheet per table", "pair 9"),
    "pair_1/golden/ACCUM_DDL.txt": ("pair-1 golden DDL, alias map applied", "pair 1"),
    "pair_1/golden/RFC_ACCUMULATORS_IIG.xlsx": ("pair-1 golden IIG, alias map applied", "pair 1"),
}


def build_all() -> dict[str, bytes]:
    """Every fixture's bytes, keyed by path relative to FIXTURE_ROOT."""
    out: dict[str, bytes] = {}
    for rel, builder in sttm.BUILDERS.items():
        out[rel] = xlsx_bytes(builder())
    for rel, builder in vdd.BUILDERS.items():
        out[rel] = xlsx_bytes(builder())
    for rel, builder in frd.BUILDERS.items():
        out[rel] = builder()
    ddl = (GOLDEN_SOURCE / "ACCUM_DDL.txt").read_bytes().decode("utf-8")
    out["pair_1/golden/ACCUM_DDL.txt"] = pair1.alias_golden_ddl(ddl).encode("utf-8")
    out["pair_1/golden/RFC_ACCUMULATORS_IIG.xlsx"] = pair1.alias_golden_iig(
        GOLDEN_SOURCE / "RFC_ACCUMULATORS_IIG.xlsx")
    assert set(out) == set(FAMILY), sorted(set(out) ^ set(FAMILY))
    return out


def materialize(root: Path = FIXTURE_ROOT) -> list[Path]:
    written = []
    for rel, data in build_all().items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        written.append(path)
    return written
